format = """
[▓](yellow)\
$os\
[ ](bg:green fg:yellow)\
$directory\
[ ](bg:sapphire fg:green)\
$git_branch\
[ ](bg:lavender fg:sapphire)\
$git_status\
$git_state\
[  ](fg:lavender)\
"""

right_format = """
[  ](fg:green)\
$status
$nodejs\
$python\
[](bg: green)
"""

palette = 'catppuccin_frappe'

[git_branch]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol $branch ](fg:crust bg:sapphire)]($style)'
truncation_length = 15
truncation_symbol = '…'

[git_status]
style = "bg:lavender"
format = '[[ ($all_status$ahead_behind )](fg:crust bg:lavender)]($style)'

[git_state]
style = "bg:lavender"
format = '[\($state( $progress_current/$progress_total)\) ]($style)'
[nodejs]
symbol = ""
style = "bg:green"
format = """
[[ $symbol( $version) ](fg:crust bg:green)]($style)
"""

[os]
style = "bg:yellow fg:crust"
format = '[ $symbol]($style)'
disabled = false

[username]
style_user = "bg:yellow fg:crust"
format = '[$user ]($style)' 
[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol \(#$virtualenv\) ](fg:crust bg:green)]($style)'

[directory]
style = "bg:green fg:crust"
format = "[ $path ]($style)"

[os.symbols]
Macos = " "
Ubuntu = " "

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
